### PR TITLE
Add getters and setters for frequency correction

### PR DESCRIPTION
**Pull request by tenderlove**
I need to set PPM values for my radio, so I'm adding the getters /
setters for it.

### CODE REVIEW

**Comment by tjarratt** [comment]
Wow, thank you @tenderlove. It's not every day I wake up with a pull request in my inbox from an literal internet celebrity on a repo I wrote seven years ago and haven't touched since. 

There have been a lot of memes going around about how 2021 is going to be better than 2020, but honestly if this is a sign of things to come, I am very much looking forward to this year.

This change looks good to me, and easy enough to merge. I unfortunately don't have a radio I can test this with anymore, so I'm going to have to trust you that this works.

**Comment by tjarratt** [comment]
If I may ask, I'm really curious how you found this repo in the first place @tenderlove. This seems like a pretty obscure and niche area, and in the 7 years since I wrote this code this has been the first PR. What kind of radio projects are you working on ? Is [Adequate Co](https://twitter.com/LightfootJaime/status/998968476206219264) branching out into the radio space ?

**Comment by tenderlove** [comment]
> If I may ask, I'm really curious how you found this repo in the first place @tenderlove. This seems like a pretty obscure and niche area, and in the 7 years since I wrote this code this has been the first PR. What kind of radio projects are you working on ? Is [Adequate Co](https://twitter.com/LightfootJaime/status/998968476206219264) branching out into the radio space ?

Honestly I'm just messing around with an SDR dongle in my spare time. I want to port [this webpage](https://witestlab.poly.edu/blog/capture-and-decode-fm-radio/) and [these examples](https://pysdr.org) to Ruby.  Eventually I'd like to do more DSP stuff with Ruby, and eventually some digital communications.

**Comment by tjarratt** [comment]
Cool stuff. I took a look at that webpage and even having studied complex analysis and done some some amateur level SDR in the past, it all went over my head. 

I wish you good luck ! If by chance there's anything I can do to help out from this repo, let me know.

**Pull request merged**
